
export const accessories = [
  {
    "id": "straw-hat",
    "name": "Straw Hat",
    "world": "World 1",
    "boss": "Kid Kohan",
    "rarity": "C-Rank",
    "coins_bonus": "0.1",
    "energy_bonus": "0.01x",
    "exp_bonus": "1.0%",
    "damage_bonus": "0.05x",
    "movespeed_bonus": "10%"
  },
  {
    "id": "shinigami-scarf",
    "name": "Shinigami Scarf",
    "world": "World 3",
    "boss": "Eizen",
    "rarity": "B-Rank",
    "coins_bonus": "0.5",
    "energy_bonus": "0.05x",
    "exp_bonus": "2.5%",
    "damage_bonus": "0.1x",
    "movespeed_bonus": "25%"
  },
  {
    "id": "cursed-blindfold",
    "name": "Cursed Blindfold",
    "world": "World 4",
    "boss": "Sakuni",
    "rarity": "B-Rank",
    "coins_bonus": "0.75",
    "energy_bonus": "0.075x",
    "exp_bonus": "3.5%",
    "damage_bonus": "0.15x",
    "movespeed_bonus": "35%"
  },
  {
    "id": "clover-pendant",
    "name": "Clover Pendant",
    "world": "World 7",
    "boss": "Novi Chroni",
    "rarity": "A-Rank",
    "coins_bonus": "1.0",
    "energy_bonus": "0.1x",
    "exp_bonus": "5.0%",
    "damage_bonus": "0.25x",
    "movespeed_bonus": "50%"
  },
  {
    "id": "akatsuki-cloak",
    "name": "Akatsuki Cloak",
    "world": "World 8",
    "boss": "Itechi",
    "rarity": "A-Rank",
    "coins_bonus": "1.25",
    "energy_bonus": "0.15x",
    "exp_bonus": "5.0%",
    "damage_bonus": "0.3x",
    "movespeed_bonus": "50%"
  },
  {
    "id": "soul-reaper-cloak",
    "name": "Soul Reaper Cloak",
    "world": "World 10",
    "boss": "Ken Turbo",
    "rarity": "S-Rank",
    "coins_bonus": "1.5",
    "energy_bonus": "0.25x",
    "exp_bonus": "7.5%",
    "damage_bonus": "0.5x",
    "movespeed_bonus": "75%"
  },
  {
    "id": "hunter-license",
    "name": "Hunter License",
    "world": "World 11",
    "boss": "Killas Godspeed",
    "rarity": "S-Rank",
    "coins_bonus": "1.75",
    "energy_bonus": "0.35x",
    "exp_bonus": "7.5%",
    "damage_bonus": "0.6x",
    "movespeed_bonus": "75%"
  },
  {
    "id": "sins-emblem",
    "name": "Sins Emblem",
    "world": "World 13",
    "boss": "Esanor",
    "rarity": "SS-Rank",
    "coins_bonus": "2.0",
    "energy_bonus": "0.5x",
    "exp_bonus": "7.5%",
    "damage_bonus": "0.75x",
    "movespeed_bonus": "75%"
  },
  {
    "id": "virtual-headset",
    "name": "Virtual Headset",
    "world": "World 15",
    "boss": "The Paladin",
    "rarity": "SS-Rank",
    "coins_bonus": "2.25",
    "energy_bonus": "0.75x",
    "exp_bonus": "7.5%",
    "damage_bonus": "1x",
    "movespeed_bonus": "75%"
  },
  { "id": "scout-cloak-1", "name": "Scout Cloak", "world": "World 11", "boss": "Eran", "rarity": "Common", "energy_bonus": "0.1x" },
  { "id": "scout-cloak-2", "name": "Scout Cloak", "world": "World 11", "boss": "Eran", "rarity": "Uncommon", "energy_bonus": "0.15x" },
  { "id": "scout-cloak-3", "name": "Scout Cloak", "world": "World 11", "boss": "Eran", "rarity": "Rare", "energy_bonus": "0.2x" },
  { "id": "scout-cloak-4", "name": "Scout Cloak", "world": "World 11", "boss": "Eran", "rarity": "Epic", "energy_bonus": "0.25x" },
  { "id": "scout-cloak-5", "name": "Scout Cloak", "world": "World 11", "boss": "Eran", "rarity": "Legendary", "energy_bonus": "0.3x" },
  { "id": "scout-cloak-6", "name": "Scout Cloak", "world": "World 11", "boss": "Eran", "rarity": "Mythic", "energy_bonus": "0.35x" },
  { "id": "scout-cloak-7", "name": "Scout Cloak", "world": "World 11", "boss": "Eran", "rarity": "Phantom", "energy_bonus": "0.5x" },
  { "id": "scout-cloak-8", "name": "Scout Cloak", "world": "World 11", "boss": "Eran", "rarity": "Supreme", "energy_bonus": "0.75x" },
  { "id": "pokita-slides-1", "name": "Pokita Slides", "world": "World 18", "boss": "Benji", "rarity": "Common", "movespeed_bonus": "13.3%", "energy_bonus": "0.3x" },
  { "id": "pokita-slides-2", "name": "Pokita Slides", "world": "World 18", "boss": "Benji", "rarity": "Uncommon", "movespeed_bonus": "20.0%", "energy_bonus": "0.45x" },
  { "id": "pokita-slides-3", "name": "Pokita Slides", "world": "World 18", "boss": "Benji", "rarity": "Rare", "movespeed_bonus": "26.7%", "energy_bonus": "0.6x" },
  { "id": "pokita-slides-4", "name": "Pokita Slides", "world": "World 18", "boss": "Benji", "rarity": "Epic", "movespeed_bonus": "33.3%", "energy_bonus": "0.75x" },
  { "id": "pokita-slides-5", "name": "Pokita Slides", "world": "World 18", "boss": "Benji", "rarity": "Legendary", "movespeed_bonus": "40.0%", "energy_bonus": "0.9x" },
  { "id": "pokita-slides-6", "name": "Pokita Slides", "world": "World 18", "boss": "Benji", "rarity": "Mythic", "movespeed_bonus": "46.7%", "energy_bonus": "1.05x" },
  { "id": "pokita-slides-7", "name": "Pokita Slides", "world": "World 18", "boss": "Benji", "rarity": "Phantom", "movespeed_bonus": "66.7%", "energy_bonus": "1.5x" },
  { "id": "pokita-slides-8", "name": "Pokita Slides", "world": "World 18", "boss": "Benji", "rarity": "Supreme", "movespeed_bonus": "100.0%", "energy_bonus": "2.25x" },
  { "id": "scarffy-1", "name": "Scarffy", "world": "World 20", "boss": "Young Kohan", "rarity": "Common", "damage_bonus": "0.133x", "coins_bonus": "0.6", "exp_bonus": "2.0%" },
  { "id": "scarffy-2", "name": "Scarffy", "world": "World 20", "boss": "Young Kohan", "rarity": "Uncommon", "damage_bonus": "0.2x", "coins_bonus": "0.9", "exp_bonus": "3.0%" },
  { "id": "scarffy-3", "name": "Scarffy", "world": "World 20", "boss": "Young Kohan", "rarity": "Rare", "damage_bonus": "0.267x", "coins_bonus": "1.2", "exp_bonus": "4.0%" },
  { "id": "scarffy-4", "name": "Scarffy", "world": "World 20", "boss": "Young Kohan", "rarity": "Epic", "damage_bonus": "0.333x", "coins_bonus": "1.5", "exp_bonus": "5.0%" },
  { "id": "scarffy-5", "name": "Scarffy", "world": "World 20", "boss": "Young Kohan", "rarity": "Legendary", "damage_bonus": "0.4x", "coins_bonus": "1.8", "exp_bonus": "6.0%" },
  { "id": "scarffy-6", "name": "Scarffy", "world": "World 20", "boss": "Young Kohan", "rarity": "Mythic", "damage_bonus": "0.467x", "coins_bonus": "2.1", "exp_bonus": "7.0%" },
  { "id": "scarffy-7", "name": "Scarffy", "world": "World 20", "boss": "Young Kohan", "rarity": "Phantom", "damage_bonus": "0.667x", "coins_bonus": "3", "exp_bonus": "10.0%" },
  { "id": "scarffy-8", "name": "Scarffy", "world": "World 20", "boss": "Young Kohan", "rarity": "Supreme", "damage_bonus": "1x", "coins_bonus": "4.5", "exp_bonus": "15.0%" },
  { "id": "fire-force-pants-1", "name": "Fire Force Pants", "world": "World 19", "boss": "Shinro", "rarity": "Common", "energy_bonus": "0.133x" },
  { "id": "fire-force-pants-2", "name": "Fire Force Pants", "world": "World 19", "boss": "Shinro", "rarity": "Uncommon", "energy_bonus": "0.2x" },
  { "id": "fire-force-pants-3", "name": "Fire Force Pants", "world": "World 19", "boss": "Shinro", "rarity": "Rare", "energy_bonus": "0.267x" },
  { "id": "fire-force-pants-4", "name": "Fire Force Pants", "world": "World 19", "boss": "Shinro", "rarity": "Epic", "energy_bonus": "0.333x" },
  { "id": "fire-force-pants-5", "name": "Fire Force Pants", "world": "World 19", "boss": "Shinro", "rarity": "Legendary", "energy_bonus": "0.4x" },
  { "id": "fire-force-pants-6", "name": "Fire Force Pants", "world": "World 19", "boss": "Shinro", "rarity": "Mythic", "energy_bonus": "0.467x" },
  { "id": "fire-force-pants-7", "name": "Fire Force Pants", "world": "World 19", "boss": "Shinro", "rarity": "Phantom", "energy_bonus": "0.667x" },
  { "id": "fire-force-pants-8", "name": "Fire Force Pants", "world": "World 19", "boss": "Shinro", "rarity": "Supreme", "energy_bonus": "1x" },
  { "id": "fire-witch-hat-1", "name": "Fire Witch Hat", "world": "World 19", "boss": "Witch Queen", "rarity": "Common", "damage_bonus": "0.1x", "coins_bonus": "0.133" },
  { "id": "fire-witch-hat-2", "name": "Fire Witch Hat", "world": "World 19", "boss": "Witch Queen", "rarity": "Uncommon", "damage_bonus": "0.15x", "coins_bonus": "0.2" },
  { "id": "fire-witch-hat-3", "name": "Fire Witch Hat", "world": "World 19", "boss": "Witch Queen", "rarity": "Rare", "damage_bonus": "0.2x", "coins_bonus": "0.267" },
  { "id": "fire-witch-hat-4", "name": "Fire Witch Hat", "world": "World 19", "boss": "Witch Queen", "rarity": "Epic", "damage_bonus": "0.25x", "coins_bonus": "0.333" },
  { "id":